version: "3"

services:

 zookeeper:
  image: bitnami/zookeeper
  platform: linux/amd64
  container_name: zookeeper-main
  environment:
   ALLOW_ANONYMOUS_LOGIN: yes

 kafka-node:
  image: bitnami/kafka
  platform: linux/amd64
  environment:
   ALLOW_PLAINTEXT_LISTENER: yes
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   JMX_PORT: 8004
  depends_on: 
   - zookeeper

 cmak:
  image: rathnaviraj/cmak
  container_name: cmak-main
  environment:
   ZK_HOSTS: zookeeper:2181
  ports:
   - 9000:9000
  depends_on:
   - zookeeper
   - kafka-node
